/**
 * Templates table queries.
 *
 * @module modules/cards/db/templates
 * @description Pure SQL functions for the `templates` table.
 */

import type { Sql } from '@/shared/db/client';

export interface TemplatesRow {
  id: string;
  tenant_id: string;
  status: 'draft' | 'published';
  name: string;
  card_type: CardType;
  settings: TemplateSettings;
  created_at: Date;
  updated_at: Date;
}

/** Card types supported by the card builder */
export type CardType =
  | 'stamp_card'
  | 'cashback_card'
  | 'reward_card'
  | 'membership_card'
  | 'discount_card'
  | 'coupon_card'
  | 'multipass'
  | 'gift_card';

/**
 * Template settings — flat JSONB structure.
 *
 * Step 1: name, cardType
 * Step 2: barcodeType, storeName, issuerName, passValidDays, expiryDate, currency
 * Step 3-4: TBD (backgroundColor, textColor, etc.)
 */
export interface TemplateSettings {
  name?: string;
  cardType?: CardType;
  barcodeType?: 'qr_code' | 'pdf_417';
  storeName?: string;
  issuerName?: string;
  passValidDays?: number | null;
  expiryDate?: string;
  currency?: 'TWD' | 'ZAR';
  // Step 3-4 fields (TBD)
  issuerLogo?: string;
  backgroundColor?: string;
  textColor?: string;
  holderName?: string;
  cardSide?: 'front' | 'back';
}

/** Input for creating a new template */
export interface CreateTemplateInput {
  tenantId: string;
  name?: string;
  cardType: CardType;
  settings?: Partial<TemplateSettings>;
}

/** Input for updating a template */
export interface UpdateTemplateInput {
  name?: string;
  cardType?: CardType;
  settings?: Partial<TemplateSettings>;
  status?: 'draft' | 'published';
}

/**
 * Insert a new template row.
 * UUID is generated by the DB via DEFAULT gen_random_uuid().
 */
export async function insertTemplate(
  sql: Sql,
  input: CreateTemplateInput,
): Promise<TemplatesRow> {
  const rows = await sql<TemplatesRow[]>`
    INSERT INTO templates (
      tenant_id,
      name,
      card_type,
      settings
    ) VALUES (
      ${input.tenantId},
      ${input.name ?? '未命名卡片'},
      ${input.cardType},
      ${JSON.stringify(input.settings ?? {})}::jsonb
    )
    RETURNING id, tenant_id, status, name, card_type, settings, created_at, updated_at
  `;
  if (!rows[0]) {
    throw new Error('insertTemplate returned no rows');
  }
  return rows[0];
}

/**
 * Find a template by ID.
 * Returns undefined if not found.
 */
export async function findTemplateById(
  sql: Sql,
  id: string,
): Promise<TemplatesRow | undefined> {
  const rows = await sql<TemplatesRow[]>`
    SELECT id, tenant_id, status, name, card_type, settings, created_at, updated_at
      FROM templates
     WHERE id = ${id}
     LIMIT 1
  `;
  return rows[0];
}

/**
 * Find all templates belonging to a tenant.
 * Ordered by updated_at DESC (most recent first).
 */
export async function findTemplatesByTenantId(
  sql: Sql,
  tenantId: string,
): Promise<TemplatesRow[]> {
  const rows = await sql<TemplatesRow[]>`
    SELECT id, tenant_id, status, name, card_type, settings, created_at, updated_at
      FROM templates
     WHERE tenant_id = ${tenantId}
     ORDER BY updated_at DESC
  `;
  return rows;
}

/**
 * Update a template by ID.
 * Only updates fields that are explicitly provided.
 */
export async function updateTemplate(
  sql: Sql,
  id: string,
  input: UpdateTemplateInput,
): Promise<TemplatesRow> {
  const sets: string[] = [];
  const values: unknown[] = [];
  let idx = 1;

  if (input.name !== undefined) {
    sets.push(`name = $${idx++}`);
    values.push(input.name);
  }
  if (input.cardType !== undefined) {
    sets.push(`card_type = $${idx++}`);
    values.push(input.cardType);
  }
  if (input.settings !== undefined) {
    sets.push(`settings = $${idx++}`);
    values.push(JSON.stringify(input.settings));
  }
  if (input.status !== undefined) {
    sets.push(`status = $${idx++}`);
    values.push(input.status);
  }

  if (sets.length === 0) {
    throw new Error('updateTemplate: no fields to update');
  }

  // Append id as the last parameter
  values.push(id);

  const rows = await sql<TemplatesRow[]>`
    UPDATE templates
       SET ${sql.unsafe(sets.join(', '))}
     WHERE id = $${idx - 1}
    RETURNING id, tenant_id, status, name, card_type, settings, created_at, updated_at
  `;
  if (!rows[0]) {
    throw new Error('updateTemplate: template not found');
  }
  return rows[0];
}

/**
 * Delete a template by ID.
 */
export async function deleteTemplate(sql: Sql, id: string): Promise<void> {
  await sql`DELETE FROM templates WHERE id = ${id}`;
}
