/**
 * Templates table queries.
 *
 * @module modules/cards/db/templates
 * @description Pure SQL functions for the `templates` table.
 */

import type { Sql } from '@/shared/db/client';

export interface TemplatesRow {
  id: string;
  tenant_id: string;
  status: 'draft' | 'published';
  name: string;
  /** Card type. NULL = user has not selected a type yet (orphan draft). */
  card_type?: CardType;
  settings: TemplateSettings;
  created_at: Date;
  updated_at: Date;
  /** TTL for draft templates. NULL = no expiration. Auto-set on insert, cleared on publish. */
  expires_at?: Date;
}

/** Card types supported by the card builder */
export type CardType =
  | 'stamp_card'
  | 'cashback_card'
  | 'reward_card'
  | 'membership_card'
  | 'discount_card'
  | 'coupon_card'
  | 'multipass'
  | 'gift_card';

/**
 * Template settings — flat JSONB structure.
 *
 * Step 1: name, cardType
 * Step 2: barcodeType, storeName, issuerName, passValidDays, expiryDate, currency
 * Step 3-4: TBD (backgroundColor, textColor, etc.)
 */
export interface TemplateSettings {
  name?: string;
  cardType?: CardType;
  barcodeType?: 'qr_code' | 'pdf_417';
  storeName?: string;
  issuerName?: string;
  passValidDays?: number | null;
  expiryDate?: string;
  currency?: 'TWD' | 'ZAR';
  // Step 3-4 fields (TBD)
  issuerLogo?: string;
  backgroundColor?: string;
  textColor?: string;
  holderName?: string;
  cardSide?: 'front' | 'back';
}

/** Input for creating a new template */
export interface CreateTemplateInput {
  tenantId: string;
  name?: string;
  /** Card type. NULL = user has not selected a type yet. */
  cardType?: CardType;
  settings?: Partial<TemplateSettings>;
  /** ISO 8601 timestamp. Defaults to now() + 24h in insertTemplate. */
  expiresAt?: string;
}

/** Input for updating a template */
export interface UpdateTemplateInput {
  name?: string;
  cardType?: CardType;
  settings?: Partial<TemplateSettings>;
  status?: 'draft' | 'published';
}

/**
 * Insert a new template row.
 * UUID is generated by the DB via DEFAULT gen_random_uuid().
 * expires_at is auto-set to now() + 24h (draft TTL).
 */
export async function insertTemplate(
  sql: Sql,
  input: CreateTemplateInput,
): Promise<TemplatesRow> {
  const rows = await sql<TemplatesRow[]>`
    INSERT INTO templates (
      tenant_id,
      name,
      card_type,
      settings,
      expires_at
    ) VALUES (
      ${input.tenantId},
      ${input.name ?? '未命名卡片'},
      ${input.cardType ?? null},
      ${JSON.stringify(input.settings ?? {})}::jsonb,
      ${input.expiresAt ?? sql`(now() + interval '24 hours')`}
    )
    RETURNING id, tenant_id, status, name, card_type, settings, created_at, updated_at, expires_at
  `;
  if (!rows[0]) {
    throw new Error('insertTemplate returned no rows');
  }
  return rows[0];
}

/**
 * Find a template by ID.
 * Returns undefined if not found.
 */
export async function findTemplateById(
  sql: Sql,
  id: string,
): Promise<TemplatesRow | undefined> {
  const rows = await sql<TemplatesRow[]>`
    SELECT id, tenant_id, status, name, card_type, settings, created_at, updated_at, expires_at
      FROM templates
     WHERE id = ${id}
     LIMIT 1
  `;
  return rows[0];
}

/**
 * Find all templates belonging to a tenant.
 * Ordered by updated_at DESC (most recent first).
 */
export async function findTemplatesByTenantId(
  sql: Sql,
  tenantId: string,
): Promise<TemplatesRow[]> {
  const rows = await sql<TemplatesRow[]>`
    SELECT id, tenant_id, status, name, card_type, settings, created_at, updated_at, expires_at
      FROM templates
     WHERE tenant_id = ${tenantId}
     ORDER BY updated_at DESC
  `;
  return rows;
}

/**
 * Update a template by ID.
 * Only updates fields that are explicitly provided.
 * When status is set to 'published', expires_at is automatically cleared.
 */
export async function updateTemplate(
  sql: Sql,
  id: string,
  input: UpdateTemplateInput,
): Promise<TemplatesRow> {
  // Collect name, cardType, settings, status in tagged template to avoid $N collisions
  // with postgres.js dollar-quoting. The id is always passed as ${id} — not as a $N
  // positional placeholder — so it never collides with the column-value $1/$2/$3.
  const rows = await sql<TemplatesRow[]>`
    UPDATE templates
       SET
         ${input.name !== undefined ? sql`name = ${input.name}` : sql``}
         ${input.name !== undefined && (input.cardType !== undefined || input.settings !== undefined || input.status !== undefined) ? sql`,` : sql``}
         ${input.cardType !== undefined ? sql`card_type = ${input.cardType}` : sql``}
         ${input.cardType !== undefined && (input.settings !== undefined || input.status !== undefined) ? sql`,` : sql``}
         ${input.settings !== undefined ? sql`settings = ${JSON.stringify(input.settings)}` : sql``}
         ${input.settings !== undefined && input.status !== undefined ? sql`,` : sql``}
         ${input.status !== undefined
           ? input.status === 'published'
             ? sql`status = ${input.status}, expires_at = NULL`
             : sql`status = ${input.status}`
           : sql``}
     WHERE id = ${id}
    RETURNING id, tenant_id, status, name, card_type, settings, created_at, updated_at, expires_at
  `;

  if (!rows[0]) {
    throw new Error('updateTemplate: template not found');
  }
  return rows[0];
}

/**
 * Touch a draft template — reset its expires_at to now() + 24h.
 * Used by the frontend auto-save to keep drafts alive.
 */
export async function touchExpiresAt(
  sql: Sql,
  id: string,
): Promise<TemplatesRow> {
  const rows = await sql<TemplatesRow[]>`
    UPDATE templates
       SET expires_at = now() + interval '24 hours'
     WHERE id = ${id}
    RETURNING id, tenant_id, status, name, card_type, settings, created_at, updated_at, expires_at
  `;
  if (!rows[0]) {
    throw new Error('touchExpiresAt: template not found');
  }
  return rows[0];
}

/**
 * Delete a template by ID.
 */
export async function deleteTemplate(sql: Sql, id: string): Promise<void> {
  await sql`DELETE FROM templates WHERE id = ${id}`;
}
